<template>
  <div class="project-detail">
    <router-link to="/" class="back-link">&larr; Back to Overview</router-link>
    
    <h1>Project Log: {{ slug }}</h1>
    <p class="description">Full history log and automated social outputs generated by this pipeline.</p>

    <div class="full-feed">
      <!-- You can map through your complete posts data here -->
      <div class="feed-item">
        <span class="timestamp">2026-06-15 14:00 UTC</span>
        <p>Full generated character output log...</p>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  slug: String // Passed automatically from router URL path /project/:slug
})
</script>

<style scoped>
.back-link {
  color: #3b82f6;
  text-decoration: none;
  display: inline-block;
  margin-bottom: 1rem;
}
.feed-item {
  background-color: #1a1a1a;
  border: 1px solid #333;
  padding: 1rem;
  border-radius: 6px;
  margin-top: 1rem;
}
.timestamp {
  color: #888;
  font-size: 0.8rem;
}
</style>